La fonction 'update_home_devices' n'a pas été trouvée dans router.py.